# Generated by Django 3.2.12 on 2023-11-23 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('popis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spravuje', models.IntegerField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.system')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('popis', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.system')),
                ('uzivatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typ', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='uzivatel',
            field=models.ManyToManyField(blank=True, related_name='system', through='main.Vidi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('hodnota', models.IntegerField()),
                ('kpi_typ', models.IntegerField()),
                ('kpi_hodnota', models.IntegerField()),
                ('typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typ')),
            ],
        ),
    ]
