# Generated by Django 3.2.12 on 2023-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='kpi_hodnota',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='kpi_typ',
            field=models.IntegerField(default=0),
        ),
    ]
